import type { CloseCommand,CloseResult,NotificationView } from "./notification-outbox";
export function notificationIssue(code:string):string{
 const known:Record<string,string>={LEGACY_OUTCOME_UNKNOWN:"This older attempt has no saved provider result. Check the provider dashboard and follow up manually.",PROVIDER_RESPONSE_UNKNOWN:"The provider response was lost. It may have accepted the email; recovery will use the same message.",MISSING_PROVIDER_ID:"The provider did not return a usable message reference. Delivery is unconfirmed.",RETRY_WINDOW_CLOSED:"The confirmation is too old to retry automatically. Check provider records and follow up manually.",RETRY_KEY_EXPIRED:"The duplicate-prevention window has closed. Check provider records and follow up manually.",RETRY_LIMIT_REACHED:"Automatic retries have reached their limit. Check provider records and follow up manually.",PROVIDER_CREDENTIAL_CHANGED:"Provider access changed during recovery. Verify the original result before sending anything else.",PROVIDER_KEY_CONFLICT:"The provider found conflicting retry details. Studio support must review this message.",CONFLICTING_PROVIDER_IDS:"The provider returned conflicting message references. Studio support must review them.",ORDER_ALREADY_CLOSED:"The order was already closed, so its confirmation was not sent.",ORDER_CLOSED_OUTCOME_UNKNOWN:"The order closed while the email result was unknown. Check provider records; no automatic resend is allowed.",CONFIRMATION_TOO_OLD:"This confirmation was too old to send. Handle any follow-up manually.",INVALID_MESSAGE_CONFIGURATION:"The confirmation could not be prepared. Check the sender setup and order details.",DELIVERY_CHECK_UNAVAILABLE:"The provider status check failed. Any displayed delivery evidence is from an earlier check.",DELIVERY_RESULT_MISMATCH:"The provider result could not be matched to this confirmation. Studio support must review it."};
 if(known[code])return known[code];
 if(/^DELIVERY_CHECK_HTTP_/.test(code))return "The provider could not supply delivery status. Check that provider access allows reading email records.";
 if(/^PROVIDER_HTTP_(401|403)$/.test(code))return "Provider access or the sender configuration needs attention. Handle this confirmation manually.";
 if(code==="PROVIDER_HTTP_429")return "The provider asked us to wait before another attempt.";
 return "The provider result needs review. Check its dashboard or handle guest follow-up manually.";
}
export function notificationLabel(item:Pick<NotificationView,"status"|"providerEvent">):string {
  if(item.status==="closed")return "Manual follow-up recorded";
  if(item.providerEvent)return ({sent:"Provider accepted email; delivery unverified",delivered:"Recipient mail server accepted email",delivery_delayed:"Provider reports delivery delayed",bounced:"Provider reports email bounced",complained:"Provider reports a spam complaint",opened:"Provider reports an open event",clicked:"Provider reports a click event",failed:"Provider reports delivery failed",suppressed:"Provider suppressed email",scheduled:"Provider scheduled email",canceled:"Provider cancelled email"} as Record<string,string>)[item.providerEvent]??"Provider result needs review";
  return ({queued:"Awaiting first attempt",sending:"Provider request in progress",retry:"Result uncertain; retry pending",accepted:"Provider accepted email; delivery unverified",attempted:"Older attempt: outcome unknown",review:"Needs owner review",blocked:"Provider/configuration problem",suppressed:"Not sent: order closed or confirmation too old"} as Record<string,string>)[item.status]??"Status unknown";
}
export function readNotificationReview(raw:unknown,command:CloseCommand):CloseResult|null{
  if(!raw||typeof raw!=="object")return null;const r=raw as CloseResult,c=r.command;
  if(r.operationId!==command.operationId||r.orderId!==command.orderId||!c||Object.keys(c).length!==4||Object.keys(command).some(k=>c[k as keyof CloseCommand]!==command[k as keyof CloseCommand])||typeof r.message!=="string"||r.message.length>500)return null;
  return r.outcome==="saved"&&r.status===200||r.outcome==="rejected"&&[400,403,404,409].includes(r.status)?r:null;
}
export async function notificationReviewRequest(command:CloseCommand,check=false,fetcher:typeof fetch=fetch,timeoutMs=12000):Promise<CloseResult|null>{
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);
 try{const response=await fetcher(check?"/api/kitchen/notifications?review="+encodeURIComponent(command.operationId):"/api/kitchen/notifications",{method:check?"GET":"POST",cache:"no-store",signal:controller.signal,...(check?{}:{headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"close",command})})});const result=readNotificationReview(await response.json(),command);return (check?response.ok:response.status===result?.status)?result:null;}catch{return null;}finally{clearTimeout(timer);}
}
